### PR TITLE
[CREATED]dashboard initial layout

### PR DESCRIPTION
**Pull request by ShivamTyagi12345**
@PalakKumari   verify whether or not I am creating the components as per the required directory structure.

This is the initial layout ,if my directory structure is right I will proceed further with the css
image

### CODE REVIEW

**Review by PalakKumari — CHANGES_REQUESTED** [review]
Yes, the Folder structure is right. Try to remove all the warnings before you create a pull request to avoid failing checks in deployment( for eg: The warning for IMG tag here). Also, you're displaying static data, use props so that fetching and displaying data from the database is easier. Make your components as much dynamic as possible, and in a way that connecting your frontend to the backend is convenient.

**Comment by ShivamTyagi12345** [comment]
@PalakKumari I can see that you have requested changes but I cant see which lines of code are u asking me to change .How can see your review , Any idea?


image

**Comment by PalakKumari** [comment]
> @PalakKumari I can see that you have requested changes but I cant see which lines of code are u asking me to change .How can see your review , Any idea?
> 
> image

I've provided the description of what changes I've requested. Follow them and if you still have  any doubts we will discuss in sync-up meet

**Comment by ShivamTyagi12345** [comment]
@PalakKumari  All the props are now dynamic
Additionally i would like any other member  to take up the rest of the styling work , I can then focus on the backend work
image

**Pull request merged**
