### PR TITLE
events route created and connected with create-events form

### PR DESCRIPTION
**Pull request by Vivek3072**

### CODE REVIEW

**Comment by PalakKumari** [comment]
> _No description provided._

Add proper error handling. If the checkbox for is offline is clicked, the location must be provided else send error. One event should be created only once, if same event is already present, send error. When the checkbox for is offline is clicked, in the database is offline is saved as false. Modify your code to handle this properly. If the req method is not post, send a error response with a meaningful message.
For client-side: Add the file upload input for the event poster. Ask in case of any doubts.

**Comment by Vivek3072** [comment]
> > _No description provided._
> 
> Add proper error handling. If the checkbox for is offline is clicked, the location must be provided else send error. One event should be created only once, if same event is already present, send error. When the checkbox for is offline is clicked, in the database is offline is saved as false. Modify your code to handle this properly. If the req method is not post, send a error response with a meaningful message. For client-side: Add the file upload input for the event poster. Ask in case of any doubts.

Okay mam

**Comment by PalakKumari** [comment]
> > > _No description provided._
> > 
> > 
> > Add proper error handling. If the checkbox for is offline is clicked, the location must be provided else send error. One event should be created only once, if same event is already present, send error. When the checkbox for is offline is clicked, in the database is offline is saved as false. Modify your code to handle this properly. If the req method is not post, send a error response with a meaningful message. For client-side: Add the file upload input for the event poster. Ask in case of any doubts.
> 
> Okay mam

any updates?

**Comment by PalakKumari** [comment]
image
 everything is working fine, except for same event can be saved in the database more than once. Add a check for existing events with the same name in the events schema, and return error before saving the event in database.

**Pull request merged**
