### PR TITLE
SignUp Pop

### PR DESCRIPTION
**Pull request by vian9**

### CODE REVIEW

**Review by PalakKumari — CHANGES_REQUESTED** [review]
This is supposed to be a popup, make the cards smaller
like this:
image
 like this popup, the signup popup will appear when the signup button is clicked.

**Comment by vian9** [comment]
> This is supposed to be a popup, make the cards smaller
> like this:
> image
> like this popup, the signup popup will appear when the signup button is clicked.

Signup button is attached with props......if this is added as Popup there then on different pages also where props value is different it will show signup pop.
Screenshot 2022-01-13 at 9 19 00 PM

**Comment by PalakKumari** [comment]
> > This is supposed to be a popup, make the cards smaller
> > like this:
> > image
> > like this popup, the signup popup will appear when the signup button is clicked.
> 
> Signup button is attached with props......if this is added as Popup there then on different pages also where props value is different it will show signup pop. Screenshot 2022-01-13 at 9 19 00 PM

Navbar will be made dynamic , for now design the  popup as it is in the design.

**Comment by PalakKumari** [comment]
> > > This is supposed to be a popup, make the cards smaller
> > > like this:
> > > image
> > > like this popup, the signup popup will appear when the signup button is clicked.
> > 
> > 
> > Signup button is attached with props......if this is added as Popup there then on different pages also where props value is different it will show signup pop. Screenshot 2022-01-13 at 9 19 00 PM
> 
> Navbar will be made dynamic , for now design the popup as it is in the design.

Share Your updates

**Pull request closed without merging**
