### PR TITLE
Route Creation for Products

### PR DESCRIPTION
**Pull request by ShivamTyagi12345**
Covers 
- #57 
Deletion of products is yet to be solved

### CODE REVIEW

**Review by PalakKumari — CHANGES_REQUESTED** [review]
Add proper error handling, create a new file for this route and add the product deletion code.

**Comment by PalakKumari** [comment]
> Add proper error handling, create a new file for this route and add the product deletion code.

ask in case of any doubts.

**Comment by PalakKumari** [comment]
> > Add proper error handling, create a new file for this route and add the product deletion code.
> 
> ask in case of any doubts.

@ShivamTyagi12345  whats the progress?

**Comment by ShivamTyagi12345** [comment]
resolving the conflicting files and committing your changes

**Comment by ShivamTyagi12345** [comment]
@PalakKumari  i have resolved the conflicting files.Is there anything else to add to this PR

**Comment by PalakKumari** [comment]
> @PalakKumari i have resolved the conflicting files.Is there anything else to add to this PR

Error handling is still not done.

**Comment by PalakKumari** [comment]
> > @PalakKumari i have resolved the conflicting files.Is there anything else to add to this PR
> 
> Error handling is still not done.

It is the same code I committed to your PR.

**Comment by ShivamTyagi12345** [comment]
> e.

adding it right now

**Comment by PalakKumari** [comment]
> > e.
> 
> adding it right now

The create event file in your PR is not the updated one. Fetch upstream before creating PR.

**Comment by PalakKumari** [comment]
> > > e.
> > 
> > 
> > adding it right now
> 
> The create event file in your PR is not the updated one. Fetch upstream before creating PR.

I'm closing this PR, create a new one.

**Pull request closed without merging**
