### PR TITLE
Error handling

### PR DESCRIPTION
**Pull request by ShivamTyagi12345**

### CODE REVIEW

**Comment by ShivamTyagi12345** [comment]
i think it would be nice to remove 100 ,200 etc status code, They haven't really been used

**Comment by PalakKumari** [comment]
> i think it would be nice to remove 100 ,200 etc status code, They haven't really been used

We might need them later.

**Comment by PalakKumari** [comment]
image
image

The error handling has not been done properly. For weak password, the error response says invalid email. Also, individual and organisation dashboard routes have been merged and they have to be modified for error responses. Make sure for each response from the apis, you add user understandable error messages in the errors file and the correct responses reach the client-side. BTW fine job with the sendError function🙌

**Comment by PalakKumari** [comment]
> image image
> 
> The error handling has not been done properly. For weak password, the error response says invalid email. Also, individual and organisation dashboard routes have been merged and they have to be modified for error responses. Make sure for each response from the apis, you add user understandable error messages in the errors file and the correct responses reach the client-side. BTW fine job with the sendError function🙌

The error file contains duplicate keys. Remove that.

**Pull request merged**
